Rasta_Web/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.doc.views import doc_downloader
from apps.intro import urls as intro_urls
from apps.doc import urls as doc_url
from apps.contact_us import urls as contact_us_urls
from apps.blog import urls as blog_url
from apps.events import urls as events_url
from apps.newsletter import urls as newsletter_url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('contact_us/', include(contact_us_urls)),
    path('events/', include(events_url)),
    path('blog/', include(blog_url)),
    path('download/', doc_downloader),
    path('newsletter/', include(newsletter_url)),
    path('doc/', include(doc_url)),
    path('', include(intro_urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/intro/urls.py
from django.conf.urls import url
from django.urls import path, include
from apps.intro import views


app_name = "intro"
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^notify$', views.notify),
]

apps/newsletter/urls.py
from django.urls import path, include

from apps.newsletter import views

app_name = "newsletter"
urlpatterns = [
    path('unsubscribe/<slug:uid>/', views.unsubscribe),
]

apps/newsletter/models.py
import django
from django.db import models
import uuid

# Create your models here.
from django.utils.html import strip_tags


class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    date_joint = models.DateTimeField(default=django.utils.timezone.now)
    unique_id = models.CharField(default=str(uuid.uuid4()).replace("-", ""), max_length=200, unique=True)

    def __str__(self):
        return str(self.email)


class EmailText(models.Model):
    subject = models.CharField(null=False, blank=False, max_length=100)
    text = models.TextField(null=False, blank=False, max_length=1000)
    link = models.CharField(null=True, blank=True, max_length=400)
    link_text = models.CharField(null=True, blank=True, max_length=100)

    def __str__(self):
        return self.subject

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.pk is None:
            from apps.newsletter.tasks import send_mail_to_subscribers_task
            super(EmailText, self).save(force_insert, force_update, using, update_fields)
            context = {
                'text': self.text,
                'link': self.link,
                'link_text': self.link_text,
            }
            send_mail_to_subscribers_task.delay(context, self.subject)

apps/newsletter/views.py
from django.shortcuts import render

# Create your views here.
from apps.newsletter.models import Subscriber


def unsubscribe(request, uid):
    try:
        s = Subscriber.objects.get(unique_id=uid)
    except Subscriber.DoesNotExist:
        response = render(request, 'base/404.html')
        response.status_code = 404
        return response
    s.delete()
    return render(request, 'newsletter/unsubscribe.html')

apps/newsletter/templates/newsletter/content.html
<html lang="fa">

<head>
    <meta charset="UTF-8">

    <title>Rasta</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/icon.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet'>
      <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
            type="text/css"
    />


</head>
<body dir="rtl" style="height: 100%; background-color: #37bba0">

<div class="pusher">
    <div id="main">


        <div class="ui center aligned stackable grid" style="padding: 5%" >


    <div class="ui twelve wide column" >

        <div class="ui segment right aligned" dir="rtl" style="border-radius: 20px !important;background-color: rgba(255,255,255,0.5) !important; padding: 5% !important;">
            <h2>رستایی عزیز سلام! </h2>
        <hr class="hline">
            <p style="text-align: justify; font-size: medium;">{{ text }}</p>
             {% if link %}
              <a class="ui button" href="{{ link }}" style="background-color: #1c5951 ;color: white;font-weight: bolder;margin-top: 20px">
                    {{ link_text }}
                </a>
            {% endif %}
        <h4>اگر نمی خواهید در آینده ایمیلی از خبرنامه رستا دریافت کنید، لطفاً <a style="color: #1e70bf" href="{{ unsubscribe }}"> اینجا</a> را کلیک کنید. </h4>

    </div>

        </div>



    </div>


</div>
</div>


</body>
</html>

apps/newsletter/templates/newsletter/unsubscribe.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
{% load static %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <title>Rasta</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'semantic/semantic.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/nav.js' %}"></script>
    <link rel="stylesheet" href="{% static 'semantic/semantic.rtl.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/sidebarstyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/icon.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet'>


{% block extra_header %}{% endblock %}
     <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body dir="rtl" style="height: 100%; background-image: url({% static 'images/pattern.jpg' %})" >
<div class="ui container center aligned" style="padding-top: 100px">
    <img src="{% static 'newsletter/images/unsubscribe.png' %}" style="width: 40%" class="">
    <div><P style="font-size: 20px;font-weight: bolder;color: var(--primary-dark)"> ایمیل‌های خبرنامه برای شما ارسال نخواد شد</P></div>
    <a class="ui button" href="{% url 'intro:homepage' %}" style="background-color: var(--secondary-dark) ;color: white;font-weight: bolder;margin-top: 20px">
                    برو به صفحه اصلی سایت !
                </a>
</div>


</body>
</html>